@isTest
public class TestClassCalculationDemo {
	@isTest
    public static void addMethod(){
        CalculationDemo cd = new CalculationDemo();
        cd.add();
    }
    @isTest
    public static void subMethod(){
        CalculationDemo cd = new CalculationDemo();
        cd.sub();
    }
    @isTest
    public static void mulMethod(){
        CalculationDemo cd = new CalculationDemo();
        cd.mul();
    }
}